{
  final Thread currentThread=Thread.currentThread();
  try {
    runnable.run();
  }
 catch (  Throwable e) {
    logService.log(LogService.LOG_ERROR,currentThread + " ended abnormally with an exception",e);
  }
  logService.log(LogService.LOG_DEBUG,currentThread + " finished executing");
}
