{
  for (  final Future f : toBeCancelled) {
    f.cancel(true);
  }
  handleCallableException(causeOrException);
}
