{
  mockRetryProviderPlugin.setAborted(false).setNextRetryDate(new DateTime(clock.getUTCNow().plusDays(1)));
  mockRetryAuthorizeOperationCallback.setResult(null).setException(new PaymentApiException(ErrorCode.__UNKNOWN_ERROR_CODE,"bla bla"));
  runner.setOperationCallback(mockRetryAuthorizeOperationCallback).setContext(directPaymentStateContext);
  try {
    runner.run(true,TransactionType.AUTHORIZE,account,paymentMethodId,null,directPaymentExternalKey,directPaymentTransactionExternalKey,amount,currency,emptyProperties,null,callContext,internalCallContext);
    Assert.fail("Expected PaymentApiException...");
  }
 catch (  final PaymentApiException e) {
    final PaymentAttemptModelDao pa=paymentDao.getPaymentAttemptByTransactionExternalKey(directPaymentTransactionExternalKey,internalCallContext).get(0);
    assertEquals(pa.getTransactionExternalKey(),directPaymentTransactionExternalKey);
    assertEquals(pa.getStateName(),"RETRIED");
    assertEquals(pa.getTransactionType(),TransactionType.AUTHORIZE);
  }
}
